import g4f
from g4f.Provider import *
from g4f.models import *

models = ['Bard', 'BaseProvider', 'Berlin', 'Bing', 'ChatAnywhere',
          'ChatBase', 'Chatgpt4Online', 'ChatgptAi', 'ChatgptDemoAi',
          'ChatgptNext', 'ChatgptX', 'DeepInfra', 'FakeGpt', 'FreeGpt',
          'GeekGpt', 'GptForLove', 'GptGo', 'H2o', 'Koala', 'Liaobots',
          'Llama2', 'Model', 'ModelUtils', 'OnlineGpt', 'Phind', 'RetryProvider',
          'Union', 'Vercel', 'You', '__builtins__', '__cached__', '__doc__', '__file__',
          '__loader__', '__name__', '__package__', 
            '__spec__', '_all_models', 'annotations', 'bloom', 'claude_instant_v1',
            'claude_v1', 'claude_v2', 'code_davinci_002', 'command_light_nightly',
            'command_nightly', 'dataclass', 'default', 'falcon_40b', 'falcon_7b', 'flan_t5_xxl',
            'gpt_35_long', 'gpt_35_turbo', 'gpt_35_turbo_0613', 'gpt_35_turbo_16k', 'gpt_35_turbo_16k_0613',
            'gpt_4', 'gpt_4_0613', 'gpt_4_32k', 'gpt_4_32k_0613', 'gpt_neox_20b', 'llama13b_v2_chat', 'llama2_13b',
            'llama2_70b', 'llama2_7b', 'llama70b_v2_chat', 'llama7b_v2_chat', 'llama_13b', 'oasst_sft_1_pythia_12b',
            'oasst_sft_4_pythia_12b_epoch_35', 'palm', 'santacoder', 'text_ada_001', 'text_babbage_001', 'text_curie_001',
            'text_davinci_002', 'text_davinci_003']

Providers = ['AItianhu', 'AItianhuSpace', 'Acytoo', 'AiAsk', 'AiChatOnline', 'AiService', 'Aibn', 'Aichat', 'Ails',
             'Aivvm', 'AsyncGeneratorProvider', 'AsyncProvider', 'Bard', 'BaseProvider', 'Berlin', 'Bing', 'ChatAiGpt',
             'ChatAnywhere', 'ChatBase', 'ChatForAi', 'Chatgpt4Online', 'ChatgptAi', 'ChatgptDemo', 'ChatgptDemoAi',
             'ChatgptDuo', 'ChatgptFree', 'ChatgptLogin', 'ChatgptNext', 'ChatgptX', 'CodeLinkAva', 'Cromicle',
             'DeepInfra', 'DfeHub', 'EasyChat', 'Equing', 'FakeGpt', 'FastGpt', 'Forefront', 'FreeGpt', 'GPTalk',
             'GeekGpt', 'GetGpt', 'GptChatly', 'GptForLove', 'GptGo', 'GptGod', 'H2o', 'Hashnode', 'HuggingChat',
             'Koala', 'Komo', 'Liaobots', 'Llama2', 'Lockchat', 'MikuChat', 'MyShell', 'Myshell', 'NoowAi',
             'OnlineGpt', 'Opchatgpts', 'OpenAssistant', 'OpenaiChat', 'PerplexityAi', 'Phind', 'Poe',
             'ProviderUtils', 'Raycast', 'RetryProvider', 'TalkAi', 'Theb', 'ThebApi', 'V50', 'Vercel',
             'Vitalentum', 'Wewordle', 'Wuguokai', 'Ylokh', 'You', 'Yqcloud', '__all__', '__annotations__',
             '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__map__', '__modules__',
             '__name__', '__package__', '__path__', '__providers__', '__spec__', 'annotations', 'base_provider',
             'deprecated', 'helper', 'needs_auth', 'retry_provider', 'sys', 'unfinished', 'webdriver']

        models = [
            g4f.models.default ,
            'gpt-3.5-turbo',
            'gpt-3.5-turbo-0613',
            'gpt-3.5-turbo-16k',
            'gpt-3.5-turbo-16k-0613',
            'gpt-4',
            'gpt-4-0613',
            'gpt-4-32k',
            'gpt-4-32k-0613',
            'palm2',
            'palm',
            'google',
            'google-bard',
            'google-palm',
            'bard',
            'llama2-7b',
            'llama2-13b'
            'llama2-70b',
            'command-nightly',
            'gpt-neox-20b',
            'santacoder',
            'bloom',
            'flan-t5-xxl',
            'code-davinci-002',
            'text-ada-001',
            'text-babbage-001',
            'text-curie-001',
            'text-davinci-002',
            'text-davinci-003',
            'llama70b-v2-chat',
            'llama13b-v2-chat',
            'llama7b-v2-chat',
            'oasst-sft-1-pythia-12b',
            'oasst-sft-4-pythia-12b-epoch-3.5',
            'command-light-nightly',
        ]